# Generated by Django 3.2.20 on 2026-01-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organisation_url',
        ),
    ]
