# Generated by Django 3.2.20 on 2026-01-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20260114_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='testing_type',
            field=models.CharField(blank=True, choices=[('white_box', 'White Box'), ('grey_box', 'Grey Box'), ('black_box', 'Black Box')], max_length=20, null=True),
        ),
    ]
