# Generated by Django 3.2.20 on 2026-02-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_testing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='testing_type',
        ),
    ]
