# Generated by Django 3.2.25 on 2026-02-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_testing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_provider',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('google', 'Google'), ('microsoft_teams', 'Microsoft Teams'), ('slack', 'Slack'), ('jira', 'Jira')], default='email', max_length=50),
        ),
    ]
