# Generated by Django 3.2.25 on 2026-03-18 12:45

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_slack_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ms_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ms_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slack_bot_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='AdminProjectDetail',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('banking_finance', 'Banking & Finance'), ('healthcare', 'Healthcare'), ('ecommerce', 'E-Commerce'), ('government', 'Government'), ('telecom', 'Telecom'), ('manufacturing', 'Manufacturing'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_project_details',
            },
        ),
    ]
