# Generated by Django 3.2.25 on 2026-08-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_ms_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ms_teams_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # NOTE: the auto-detected AlterField on signupotpsession.id (a
        # no-op DEFAULT_AUTO_FIELD bookkeeping change, unrelated to this
        # migration's actual purpose) is deliberately dropped here — djongo
        # can't translate an ALTER COLUMN TYPE statement and crashes on it.
        # State stays consistent since the field's Python-level definition
        # never actually changed.
    ]
