# Generated by Django 3.2.25 on 2026-09-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20260822_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupotpsession',
            name='invite_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        # The auto-detected AlterField on `id` (AutoField -> BigAutoField,
        # from DEFAULT_AUTO_FIELD) is dropped — djongo can't translate an
        # "ALTER COLUMN ... TYPE" statement and the migration hard-crashes
        # on it. Mongo is schemaless so there's no real column type to
        # change anyway; harmless to skip.
    ]
