# Generated by Django 3.2.25 on 2026-09-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20260901_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='magic_link_unlimited',
            field=models.BooleanField(default=False),
        ),
        # AlterField on signupotpsession.id removed — djongo can't translate
        # an ALTER COLUMN ... TYPE for an existing field (same djongo
        # limitation hit in 0014_auto_20260901_0937), and this field itself
        # isn't touched by this migration's real change anyway.
    ]
