# Generated by Django 3.2.25 on 2026-10-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20260903_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promo_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # The auto-detected AlterField on signupotpsession.id (pre-existing
        # drift, unrelated to this migration's actual change) is dropped —
        # djongo's SQL->Mongo translator cannot execute an ALTER COLUMN
        # TYPE statement (confirmed against production: SQLDecodeError,
        # "Unknown token: TYPE"), so including it here only blocks this
        # migration from ever being recorded as applied.
    ]
