# Generated by Django 3.2.25 on 2026-08-17 14:35

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'billing_stripe_webhook_events',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('freemium', 'Freemium'), ('premium', 'Premium'), ('custom', 'Custom')], max_length=20)),
                ('mode', models.CharField(blank=True, choices=[('management', 'Management'), ('management_testing', 'Management + Testing')], max_length=30, null=True)),
                ('billing_cycle', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], max_length=20, null=True)),
                ('asset_count', models.IntegerField(default=0)),
                ('price_per_ip', models.CharField(blank=True, max_length=30, null=True)),
                ('amount_due', models.CharField(default='0.00', max_length=30)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='incomplete', max_length=20)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_subscription_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('estimated_assets', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_sales_leads',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('stripe_invoice_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(default='0.00', max_length=30)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('asset_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('failed', 'Failed'), ('void', 'Void')], default='open', max_length=20)),
                ('hosted_invoice_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'db_table': 'billing_invoices',
            },
        ),
        migrations.CreateModel(
            name='BillingCustomer',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_customers',
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['admin', 'status'], name='billing_sub_admin_i_3687cd_idx'),
        ),
    ]
