# Generated by Django 3.2.20 on 2026-01-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='select_location',
        ),
    ]
