# Generated by Django 3.2.25 on 2026-02-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_details', '0002_auto_20260119_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='userdetail',
            name='team_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
