# Generated by Django 3.2.20 on 2026-01-23 13:41

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('internal_ip', 'Internal IP Address'), ('external_ip', 'External IP Address'), ('web_url', 'Web URL')], db_index=True, max_length=20)),
                ('target_value', models.CharField(db_index=True, max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scope',
            },
        ),
        migrations.AddIndex(
            model_name='scope',
            index=models.Index(fields=['admin', 'target_type'], name='scope_admin_i_78ddf0_idx'),
        ),
        migrations.AddIndex(
            model_name='scope',
            index=models.Index(fields=['admin', 'target_value'], name='scope_admin_i_94d26a_idx'),
        ),
        migrations.AddIndex(
            model_name='scope',
            index=models.Index(fields=['admin', 'is_active'], name='scope_admin_i_c80f08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scope',
            unique_together={('admin', 'target_value')},
        ),
    ]
