# Generated by Django 3.2.20 on 2026-01-28 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('testing_type', models.CharField(choices=[('white_box', 'White Box'), ('grey_box', 'Grey Box'), ('black_box', 'Black Box')], default='black_box', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scopes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScopeEntry',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
                ('entry_type', models.CharField(choices=[('internal_ip', 'Internal IP'), ('external_ip', 'External IP'), ('web_url', 'Web URL'), ('mobile_url', 'Mobile URL'), ('subnet', 'Subnet')], max_length=20)),
                ('subnet_mask', models.CharField(blank=True, max_length=50, null=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scope.scope')),
            ],
            options={
                'db_table': 'scope_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
