# Generated by Django 3.2.25 on 2026-08-11 17:45

from django.db import migrations, models
import scope.models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to=scope.models.scope_source_file_path),
        ),
    ]
