# Generated by Django 3.2.20 on 2026-01-23 17:48

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scope', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeFileUpload',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('targets_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scope_file_uploads',
            },
        ),
        migrations.AddField(
            model_name='scopefileupload',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_file_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scopefileupload',
            index=models.Index(fields=['admin', 'created_at'], name='scope_file__admin_i_a4b4a7_idx'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='target_type',
            field=models.CharField(choices=[('internal_ip', 'Internal IP Address'), ('external_ip', 'External IP Address'), ('web_url', 'Web URL'), ('mobile_url', 'Mobile URL'), ('subnet', 'Subnet')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='scope',
            name='file_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_targets', to='scope.scopefileupload'),
        ),
    ]
