# Generated by Django 3.2.20 on 2026-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0002_auto_20260123_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='subnet_count',
            field=models.IntegerField(blank=True, help_text='Number of IPs in subnet (only for subnets)', null=True),
        ),
        migrations.AddIndex(
            model_name='scope',
            index=models.Index(fields=['file_upload'], name='scope_file_up_ee99ab_idx'),
        ),
    ]
