# Generated by Django 3.2.25 on 2026-08-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0002_scope_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scope',
            name='fulfilled_report_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
