# Generated by Django 3.2.20 on 2026-01-24 19:52

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0003_auto_20260123_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='testing_type',
            field=djongo.models.fields.JSONField(blank=True, default=list, help_text='List of testing types: white_box, grey_box, black_box'),
        ),
    ]
