# Generated by Django 3.2.25 on 2026-08-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0003_auto_20260827_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeentry',
            name='expanded_from',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
