# Generated by Django 3.2.20 on 2026-01-24 20:06

from django.db import migrations, models
import djongo.models.fields


def convert_testing_type_to_string(apps, schema_editor):
    """
    Convert testing_type from JSON array to single string.
    If it's a list, take the first element. If it's already a string, keep it.
    Uses raw MongoDB operations to bypass Django field validation.
    """
    from django.db import connection
    from django.conf import settings
    import pymongo
    
    # Get MongoDB connection from Djongo
    db_wrapper = connection
    client = db_wrapper.client_connection
    db_name = settings.DATABASES['default']['NAME']
    db = client[db_name]
    collection = db['scope']
    
    # Get all documents
    documents = collection.find({})
    
    for doc in documents:
        testing_type = doc.get('testing_type')
        new_value = None
        
        # If it's a list/array, take the first element
        if isinstance(testing_type, list):
            if len(testing_type) > 0:
                # Take first valid testing type
                first_val = testing_type[0]
                if first_val in ['white_box', 'grey_box', 'black_box']:
                    new_value = first_val
        # If it's already a string, validate it
        elif isinstance(testing_type, str):
            if testing_type in ['white_box', 'grey_box', 'black_box']:
                new_value = testing_type
        
        # Update the document directly in MongoDB
        collection.update_one(
            {'_id': doc['_id']},
            {'$set': {'testing_type': new_value}}
        )


def reverse_convert_testing_type_to_list(apps, schema_editor):
    """
    Reverse: Convert single string back to JSON array (for rollback).
    Uses raw MongoDB operations to bypass Django field validation.
    """
    from django.db import connection
    from django.conf import settings
    
    # Get MongoDB connection from Djongo
    db_wrapper = connection
    client = db_wrapper.client_connection
    db_name = settings.DATABASES['default']['NAME']
    db = client[db_name]
    collection = db['scope']
    
    # Get all documents
    documents = collection.find({})
    
    for doc in documents:
        testing_type = doc.get('testing_type')
        new_value = []
        
        # Convert string to list
        if isinstance(testing_type, str) and testing_type in ['white_box', 'grey_box', 'black_box']:
            new_value = [testing_type]
        
        # Update the document directly in MongoDB
        collection.update_one(
            {'_id': doc['_id']},
            {'$set': {'testing_type': new_value}}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0004_scope_testing_type'),
    ]

    operations = [
        # Step 1: Convert existing data from JSON array to string (store in temporary field)
        migrations.RunPython(
            convert_testing_type_to_string,
            reverse_convert_testing_type_to_list,
        ),
        # Step 2: Remove the old JSONField
        migrations.RemoveField(
            model_name='scope',
            name='testing_type',
        ),
        # Step 3: Add the new CharField
        migrations.AddField(
            model_name='scope',
            name='testing_type',
            field=models.CharField(
                blank=True,
                choices=[('white_box', 'White Box'), ('grey_box', 'Grey Box'), ('black_box', 'Black Box')],
                db_index=True,
                help_text='Single testing type: white_box, grey_box, or black_box',
                max_length=20,
                null=True
            ),
        ),
        # Step 4: Add index on admin and testing_type
        migrations.AddIndex(
            model_name='scope',
            index=models.Index(fields=['admin', 'testing_type'], name='scope_admin_i_b0d76d_idx'),
        ),
    ]
