# Generated by Django 3.2.25 on 2026-03-18 13:53

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingMethodology',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('testing_types', djongo.models.fields.JSONField(default=list)),
                ('assessment_categories', djongo.models.fields.JSONField(default=list)),
                ('assessment_notes', models.TextField(blank=True, null=True)),
                ('network_perspective', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('both', 'Both')], max_length=20)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('dev', 'Dev')], max_length=20)),
                ('compliance_standards', djongo.models.fields.JSONField(default=list)),
                ('compliance_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testing_methodology', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scoping_testing_methodology',
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('banking_finance', 'Banking & Finance'), ('healthcare', 'Healthcare'), ('ecommerce', 'E-Commerce'), ('government', 'Government'), ('telecom', 'Telecom'), ('manufacturing', 'Manufacturing'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoping_project_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scoping_project_details',
            },
        ),
    ]
