# Generated by Django 3.2.25 on 2026-03-19 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoping', '0004_projectdetail_is_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingmethodology',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_methodologies', to='users.user'),
        ),
    ]
