# Generated by Django 3.2.25 on 2026-03-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0005_alter_testingmethodology_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='industry_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
