# Generated by Django 3.2.20 on 2026-01-07 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadreport',
            name='file_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='uploadreport',
            index=models.Index(fields=['admin', 'file_hash'], name='upload_repo_admin_i_decbc3_idx'),
        ),
    ]
